name: Tests

on:
  push:

jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          docker buildx build --platform=linux/amd64,linux/arm64  -t test/test -o type=tar,dest=out.tar .
          cat out.tar | docker import - test/test