name: Tests

on:
  push:

jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
#       - name: Check buildx before QEMU
#         run: |
#           docker buildx inspect
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       - name: Check buildx after QEMU
#         run: |
#           docker buildx inspect
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          docker buildx build --platform=linux/amd64,linux/arm64  -t test/test:1 --push
