name: Test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Choco
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docker-desktop
